# Determinants
In the previous notebook `linalg2_matrices.ipynb`, we revised linear transformations in 2D planes and 3D spaces.

Let us now see how much linear transformations scale the areas and volumes, in 2D planes and 3D spaces respectively.

Suppose we have the linear transformation matrix 
$$
\left[ \begin{array}{cc}
    5 &0 \\
    0 &3 \\
\end{array} \right]
$$

Here, the transformation scales $ \hat{i} $ by a factor of 5, and scales $ \hat{j} $ by a factor of 3. This means that the area has been scaled by a factor of 15.

This scaling factor is known as a determinant of a transformation.

$$
det(\left[ \begin{array}{cc}
    5 &0 \\
    0 &3 \\
\end{array} \right]) = 15 * A
$$

Where $ A $ is the original matrix having the original unscaled unit vectors i.e.

$$
A = \left[ \begin{array}{cc}
    1 &0 \\
    0 &1 \\
\end{array} \right]
$$

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.style.use('seaborn-whitegrid')
import numpy as np

In [3]:
transformation_matrix = np.matrix([
    [5, 0],
    [0, 3]
])

print("Transformation Matrix: ")
print(transformation_matrix)
print("Determinant of the matrix: ")
det = np.linalg.det(transformation_matrix)
print(det)

Transformation Matrix: 
[[5 0]
 [0 3]]
Determinant of the matrix: 
15.0


We saw, in the previous notebook, that the rotation matrix about the z-axis ($ R_z $), is given by
$$
R_z = \left[ \begin{array}{ccc}
    cos(\theta) &-sin(\theta)   &0 \\
    sin(\theta) &cos(\theta)    &0 \\
    0           &0              &1 \\
    \end{array} \right]
$$
For a $ 90^\circ $ rotation about the $ z $ axis, $ R_z $ will be,
$$
R_z(90^\circ) = \left[ \begin{array}{ccc}
    0   &-1   &0 \\
    1   &0    &0 \\
    0   &0    &1 \\
    \end{array} \right]
$$

In [4]:
transformation_matrix = np.matrix([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])

print("Transformation Matrix: ")
print(transformation_matrix)
print("Determinant of the matrix: ")
det = np.linalg.det(transformation_matrix)
print(det)

Transformation Matrix: 
[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  1]]
Determinant of the matrix: 
1.0


From intuition, a $ 90^\circ $ rotation about any of the x, y, or z axes does not result in the stretching or squeezing of 2D or 3D space.

As we can see, the determinant of such a transformation matrix (here a $ 90^\circ $ rotation about z axis), is 1, indicating that the 3D space has not been stretched or squeezed in any way.

However, if we scale $ \hat{i} $ by 2 after the $ 90^\circ $ rotation about z axis, then we are stretching space, causing it to expand, and as a result the determinant should also scale.

Let's compute it:

In [6]:
transformation_matrix = np.matrix([
    [0, -1, 0],
    [1, 0, 0],
    [0, 0, 1]
])
# Let's scale basis vector i, by 2 units.
transformation_matrix[:, 0] *= 2
# Transformation matrix after rotation + scaling:
print("Transformation Matrix after rotation + scaling: ")
print(transformation_matrix)
print("Determinant of the matrix: ")
det = np.linalg.det(transformation_matrix)
print(det)

Transformation Matrix after rotation + scaling: 
[[ 0 -1  0]
 [ 2  0  0]
 [ 0  0  1]]
Determinant of the matrix: 
2.0
