In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import seaborn as sns

import numpy as np
import pandas as pd

# Inverse Matrices
Imagine a transformation $ A $ such that a vector $ \vec{x} $ is transformed to $ \vec{v} $.

In other words, $ A\vec{x} = \vec{v} $

If we have a system of equations,

$$
2x 	+ 	y 	− 	2z 	= 	3 \\
x 	− 	y 	− 	z 	= 	0 \\
x 	+ 	y 	+ 	3z 	= 	12 \\
$$

we can re-write this in the Matrix form as,

$$ 
A \vec{x} = \vec{v} \\
\left[ \begin{array}{ccc}
    2 &1 &-2 \\
    1 &-1 &-1 \\
    1 &1 &3 \\
\end{array} \right] 
\left[ \begin{array}{c}
    x \\
    y \\
    z \\
\end{array} \right] = \left[ \begin{array}{c}
    3 \\
    0 \\
    12 \\
\end{array} \right]
$$

Now imagine a transformation which can undo the transformation, such that the basis vectors $ \hat{i}, \hat{j} \text{ and } \hat{k} $ are back to their original unit magnitude and direction.

Such a transformation, is called the *Inverse*. The inverse of $ A $ is written as $ A^{-1} $.

Performing the two transformations $ A $ and $ A^{-1} $ one after the other, means that the basis vectors are first morphed, and then "un-morphed", thus essentially "doing nothing".

The matrix that corresponds to the composite transformation $ A A^{-1} $, is the matrix that transforms the basis vector matrix into itself. Essentially, it is the **Identity transformation**.

The matrix for the **Identity transformation**, called the **Identity Matrix**, represented by the notation $ I $ is, 

$$
\left[ \begin{array}{ccc}
    1 &0 &0 \\
    0 &1 &0 \\
    0 &0 &1 \\
\end{array} \right] 
$$

In [2]:
# Let's see with sample vectors and transformations
I = np.matrix([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
])
x = np.array([[3, 4, 5]]).T
print("Identity: ")
print(I)
print("Vector: ")
print(x)

v = I * x
print("Result: ")
print(v)

Identity: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Vector: 
[[3]
 [4]
 [5]]
Result: 
[[3]
 [4]
 [5]]


### Example 1: Finding Inverse

In [3]:
# Let's solve a system of equations using NumPy
A = np.matrix([
    [2, 1, -2],
    [1, -1, -1],
    [1, 1, 3],
])
B = np.array([[3, 0, 12]]).T
print("Transformation Matrix A: ")
print(A)
det = np.linalg.det(A)
print("Determinant of the matrix: ")
print(det)

A_inv = np.linalg.inv(A)
print("Inverse of A: ")
print(A_inv)

m = A * A_inv
# m = A_inv * A
print("Verification of Inverse using Identity Matrix: ")
print(m)

Transformation Matrix A: 
[[ 2  1 -2]
 [ 1 -1 -1]
 [ 1  1  3]]
Determinant of the matrix: 
-11.999999999999995
Inverse of A: 
[[ 0.16666667  0.41666667  0.25      ]
 [ 0.33333333 -0.66666667 -0.        ]
 [-0.16666667  0.08333333  0.25      ]]
Verification of Inverse using Identity Matrix: 
[[ 1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17 -1.38777878e-17  1.00000000e+00]]


In [8]:
# Now, if we want to find out which vector [x, y, z] transformed into [3, 0, 12], we can apply the inverse transformation to v, to find the original vector.
print("Now, if we want to find out which vector [x, y, z] transformed into [3, 0, 12], we can apply the inverse transformation to v, to find the original vector.")
x = A_inv * B
print("Original vector: ")
print(x)

# Verification of vector and inverse matrix using the transformation on original vector:
v = A * x
print("Verification of vector and inverse matrix using the transformation on original vector:")
print(v)
print("We can see that x = [3.5, 1, 2.5] is the solution for the system of linear equations.")
print("This indicates that the inverse of A we found is correct!")

Now, if we want to find out which vector [x, y, z] transformed into [3, 0, 12], we can apply the inverse transformation to v, to find the original vector.
Original vector: 
[[3.5]
 [1. ]
 [2.5]]
Verification of vector and inverse matrix using the transformation on original vector:
[[ 3.]
 [ 0.]
 [12.]]
We can see that x = [3.5, 1, 2.5] is the solution for the system of linear equations.
This indicates that the inverse of A we found is correct!


## Two possibilities
There are two possibilities for the transformation matrix. One where the determinant of A is non-zero, and one where it is zero.
#### 1. Determinant of Transformation matrix is Non-Zero, i.e. $ A \neq 0 $.
If the Determinant is non-zero, it means that the N-Dimensional space given by the set of N basis vectors, is **not** being transformed into a space which is less than N-dimensions. It is only being transformed into another N-Dimensional space. 

This also means that the basis vectors are an independent set of vectors, which means that there is a unique solution (unique transformation matrix) which is the inverse of the the transformation matrix.

#### 2. Determinant of Transformation matrix is Zero, i.e. $ A = 0 $.
Remember that when the Determinant is Zero, it means that atleast one of the N basis vectors in the N-dimensional space can be written as a Linear combination of the other vectors, thus indicating that the vectors are linearly dependent, and thus atleast one of the vectors' effect can be explained by a combination of the other vectors.

This means that the number of basis vectors required to cover each and every point in the new transformed space, is less than N-dimensions.

Which in turn, means that the transformation is squishing/compressing a larger dimensional space into a smaller dimensional one.

There is no "Inverse transformation", which can un-squish or de-compress a smaller dimensional space into a larger dimensional one.

**Note:** For the system of linear equations, when a transformation matrix transforms a 3-D space into a 1D space, for example, we may still have a solution to the system of equations, but a solution will only exist if the transformed vector $ \vec{v} $ lies on the 1D line.

As we saw in Example 1, the determinant was non-zero, and thus the transformation has an inverse. This means that the system of equations has a unique solution.